---
- hosts: all
  sudo: true
  roles:
    - role: checkout
      checkout_repository: 'https://github.com/gotansible/checkout.git'
      checkout_local_path: /tmp/ansible/checkout
      checkout_remote_path: /opt/myapp
      checkout_local_keep: false
