---

- name: cleanup - delete local
  sudo: false
  local_action:
    module: file
    state: absent
    path: "{{ checkout_local_path }}"
  when: not checkout_local_keep and checkout_local_path|trim|length > 1

