---

- name: dependencies
  include: depend.yml

- name: cleanup
  include: cleanup.yml

- name: git checkout
  include: git_checkout.yml

- name: copy remote
  include: copy_remote.yml
  when: checkout_remote_path|length > 0

- name: cleanup
  include: cleanup.yml

